# docker-compose.yml
version: "3.9"

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.15
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network

networks:
  my-network:
