# docker-compose.yml
version: "3.9"

services:
  vue:
    container_name: vue
    build: .
    ports:
      - 3000:3000
    env_file:
      - ./.env
    networks:
      my-network:
        aliases:
          - frontend

  nginx:
    container_name: nginx
    image: nginx:1.15
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network

networks:
  my-network:
