FROM node:lts

WORKDIR /var/www/html/app/

COPY package*.json ./
COPY . .

RUN npm ci && npm cache clean --force
RUN npm run build

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=4100

EXPOSE 4100
CMD ["npm", "run", "preview"]
