# docker-compose.yml
version: "3.9"

services:
  frontend:
    container_name: vue-green
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5052:5050
    env_file:
      - ./.env
    networks:
      my-network:
        aliases:
          - frontend
    environment:
      - TZ=Asia/Seoul

networks:
  my-network:
