# docker-compose.yml
version: "3.9"

services:
  vue:
    container_name: vue
    build: .
    ports:
      - 5050:5050
    env_file:
      - ./.env
    networks:
      my-network:
        aliases:
          - frontend

networks:
  my-network:
