# docker-compose.yml
version: "3.9"

services:
  frontend:
    container_name: vue-blue
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 5201:5200
    env_file:
      - ./.env
    networks:
      my-network:
        aliases:
          - frontend

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.15
    volumes:
      - ./nginx/default.prod.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - my-network

networks:
  my-network:
