# docker-compose.yml
version: "3.9"

services:
  frontend:
    container_name: vue-green
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 5202:5200
    env_file:
      - ./.env
    networks:
      my-network:
        aliases:
          - frontend

networks:
  my-network:
