import { DTableStyles } from "@/components/DTable";
import colors from "@/styles/colors";
import { CSSProperties } from "vue";

export const tableheaders = ref([
  {
    title: "순서",
    key: "id",
  },
  { title: "매장", key: "storeName", sotrable: false },
  { title: "적재", key: "loadingPosition" },
  { title: "완/합계", key: "count" },
  { title: "상태", key: "status" },
  { title: "사진", key: "camera", sortable: false },
]);

export function getColor(status: string) {
  if (status === "배송완") return "success";
  if (status === "배송중") return "orange";
  if (status === "피킹중") return "blue";
  if (status === "배송중") return "yellow";
}

export const tableValue = ref([
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "피킹중",
    camera: "아이콘",
  },
  {
    id: "A-2",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송완",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
  {
    id: "A-1",
    storeName: "오늘도 나는 오더해",
    loadingPosition: "내",
    count: "2/3",
    status: "배송중",
    camera: "아이콘",
  },
]);
